### PR TITLE
Workaround clang4.0 <stdatomic.h> initialization #trivial

### PR DESCRIPTION
**Pull request by bkase**
Texture fails to build with this error on clang 4.0:

```
external/Texture/pod_support/Headers/Public/AsyncDisplayKit/ASDispatch.h:32:35: error: illegal initializer type 'atomic_size_t' (aka '_Atomic(size_t)')
  __block atomic_size_t counter = ATOMIC_VAR_INIT(0);
                                  ^
In module 'std' imported from external/Texture/pod_support/Headers/Public/AsyncDisplayKit/ASStackUnpositionedLayout.h:18:
/private/var/tmp/_bazel_bkase/a00d4cbe29902fb63d5778cc19944cd2/external/clang40/bin/../include/c++/v1/atomic:1839:30: note: expanded from macro 'ATOMIC_VAR_INIT'
                             ^
1 error generated.
```

See
http://techqa.info/programming/question/38233019/Initializing-an--atomic-int--with-a-braced-constant--Is-this-valid-C-code--If-so-why-does-it-not-compile-in-clang-

Replacing the intialization with just 0 (and not the macro fixes the
error). The forum post notes:

> C11's <stdatomic.h> header defines a macro ATOMIC_VAR_INIT that's intended to be used to initialize atomic objects, with an example:
> atomic_int guide = ATOMIC_VAR_INIT(42);
> It appears to be needed for atomic objects with automatic storage duration, which doesn't apply here.

Since we don't need the automatic storage duration either, this code
should still be correct.

### CODE REVIEW

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by bkase** [comment]
@maicki looked at this with me and confirmed this should be okay

**Comment by Adlai-Holler** [comment]
@bkase We actually do need automatic storage duration on this variable =/. 

Since the current implementation of `ATOMIC_VAR_INIT` simply returns the value unaffected, I'm fine with this patch if it unblocks you, but we should add a comment explaining why we aren't using the API-provided initializer.

**Comment by Adlai-Holler** [comment]
P.S. A more complete solution to this is to move the implementation of ASDispatchApply into a .m (or .c) file so that it's never compiled by a C++ compiler.

**Comment by bkase** [comment]
@Adlai-Holler yeah it's blocking the bazel build of master -- how's that comment?

**Comment by pinterest-ios** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Any source code changes should have an entry in CHANGELOG.md or have #trivial in their title.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>
